### ISSUE TITLE
Jump to bottom

### ISSUE THREAD

**Issue by TxaliC** [jooeungen/coronaboard_kr#4]
Since the data is in ascending chronological order,
we have to scroll to the bottom
1) in the absence of a go-to-latest button, to the &
2) made even slower lately by increasing the font size of the row-number in column 1 (=fewer lines p page, more pages to scroll through)

**Comment by yjiq150** [comment]
Hi TxaliC, 
The purpose of this repository is to provide data source which can easily be processed by computer programs. 
So if you want to see the latest data easily in human friendly form, please refer to https://coronaboard.kr/en/
